export default {
    UPDATE_PROVINCE_LIST: 'UPDATE_PROVINCE_LIST',
    UPDATE_CITY_LIST: 'UPDATE_CITY_LIST',
    UPDATE_DISTRICT_LIST: 'UPDATE_DISTRICT_LIST',
    UPDATE_CURRENT_PROVINCE: 'UPDATE_CURRENT_PROVINCE',
    UPDATE_CURRENT_CITY: 'UPDATE_CURRENT_CITY',
    UPDATE_CURRENT_DISTRICT: 'UPDATE_CURRENT_DISTRICT',
};